//------------------------------------------------------------------------
// Copyright(c) 2025 Jeff.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"AbletonTimer.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"AbletonTimer VST3 (64Bit)"
#else
#define stringFileDescription	"AbletonTimer VST3"
#endif
#define stringCompanyName		"Jeff\0"
#define stringLegalCopyright	"Copyright(c) 2025 Jeff."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
